### PR TITLE
Added an optional hourly-rate-to-annual-TC calculator

### PR DESCRIPTION
**Pull request by jonahbron**
## Initially
Screenshot from 2021-03-01 20-47-56

## After clicking Calc button
Screenshot from 2021-03-01 20-48-18

### CODE REVIEW

**Comment by realjenny** [comment]
the field is called Total Annual Compensation, but then you abbreviate it as TC. Could you change it to TAC?

**Comment by jonahbron** [comment]
@realjenny Good spot.  However I think I'd rather _remove_ the "Annual" word so that it can remain "TC", to be consistent with internal comp terminology.

**Comment by realjenny** [comment]
Yes, let's be consistent with internal terms

**Review by butterflyhug — APPROVED** [review]

**Comment by jonahbron** [comment]
Changed the Annual wording and fixed the dues calc bug.

**Review by justaliu — APPROVED** [review]
FYI there's some rendering funkiness for me (Safari on Mac)
Screen Shot 2021-03-02 at 21 11 31

**Comment by jonahbron** [comment]
Ooo that is funky.  I don't have access to a Mac, is that something you might have time to fiddle with?

**Comment by justaliu** [comment]
I can look into it, but feel free to check it in first, since this isn't going live in the near future.

**Pull request merged**
