### PR TITLE
Member profile worker

### LINKED ISSUE #267: Migrate existing ACH sources to US bank methods
As mentioned in #260 and #262 , while new signups are using the new API, there are existing members who cannot manage their payment method through the Stripe portal because they are on the old Sources API.  Deleting through the portal is not possible, so it's necessary for us to design a flow for people to do outside of Stripe's portal.

https://docs.stripe.com/api/sources/detach

https://docs.stripe.com/payments/ach-debit/migrating-from-charges

### PR DESCRIPTION
**Pull request by jonahbron**
Creating a generic member profile worker that might be expanded to support other features in the future.  For now it's only intended to fix #267

### CODE REVIEW

**Review by stephenmcmurtry — APPROVED** [review]

**Comment by jonahbron** [comment]
The core flow is working now.  It can serve all users, including but not limited to those who need to delete their bank source; we should point the existing go.awu.fyi/payment link to this worker when it's launched so that we have more control over the login flow, and can tweak things as desired.  This would only replace Stripe's email verification with our own.

All that remains now is to improve the design, it does not look nice at all yet.

**Comment by jonahbron** [comment]
@shiibainu I need someone with Stripe access to add an API key to the Cloudflare worker as an encrypted env var named `STRIPE_API_KEY`:

https://dash.cloudflare.com/394d48aba686b2466fe12e540c5d9466/workers/services/view/login/production/settings/bindings

Or send it to me directly in a disappearing Signal and I can add it.

**Comment by mattrubin** [comment]
> @shiibainu I need someone with Stripe access to add an API key to the Cloudflare worker as an encrypted env var named `STRIPE_API_KEY`

@jonahbron, do you know what scopes this key needs? I can generate a new scoped key for you.

**Comment by jonahbron** [comment]
@mattrubin I'm not certain what scopes there are available, but the capabilities it needs are:

- Edit Customer objects
- Delete Source objects
- Create billing portal sessions

**Comment by jonahbron** [comment]
The current state of the function can be seen in production here:

https://login.alphabetworkersunion.workers.dev/

It can't do anything until the Stripe key is installed however.

**Pull request merged**
